<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".PhoneLoginActivity">

    <EditText
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentStart="true"
    android:layout_alignParentLeft="true"
    android:layout_alignParentTop="true"
    android:layout_marginStart="17dp"
    android:layout_marginEnd="17dp"
    android:layout_marginTop="180dp"
    android:padding="8dp"
    android:id="@+id/phone_no_input"
    android:hint="Enter your phone number"
    android:textSize="15sp"
    android:textStyle="bold"
    android:textAlignment="center"
    android:background="@drawable/input"
    android:drawableStart="@drawable/phone"
    android:drawableLeft="@drawable/phone"
    android:textAllCaps="false"
    />
    <EditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_below="@+id/phone_no_input"
        android:layout_marginStart="17dp"
        android:layout_marginEnd="17dp"
        android:layout_marginTop="8dp"
        android:padding="8dp"
        android:id="@+id/verification_code"
        android:hint="Enter the verification code here"
        android:textSize="15sp"
        android:textStyle="bold"
        android:textAlignment="center"
        android:background="@drawable/input"
        android:drawableStart="@drawable/password"
        android:textAllCaps="false"
        android:drawableLeft="@drawable/password" />
    <Button
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/send_verfication_code"
        android:background="@drawable/button"
        android:text="Send the verification code"
        android:textStyle="bold"
        android:textColor="#fff"
        android:layout_below="@+id/verification_code"
        android:layout_marginStart="17dp"
        android:layout_marginEnd="17dp"
        android:layout